### ISSUE TITLE
Component List

### ISSUE THREAD

**Issue by l2succes** [artsy/reaction-force#22]
This is a list of react components that need to be implemented based on the [artsy style guide](https://artsy-elan-production.herokuapp.com). 

So far we're attempting to leverage assets from elan, our UI library, to build out those components. We're experimenting with ways to reuse the CSS for components in elan within reaction-force using a library like [css-modules](https://github.com/css-modules/css-modules). However, it may make more sense to copy the styles directly into react components and just use [styled-components](https://github.com/styled-components/styled-components).

You can track the current process of our experiment on the following PR (https://github.com/artsy/reaction-force/pull/18). If you're working on a component, just put your name next to it so we know who's working on what.

Generic Components
- [x] Header (@xtina-starr)
- [x] Title (@xtina-starr)
- [x] Logo
- [x] Text Input (@l2succes)
- [x] Textarea (@l2succes)
- [x] Button (@l2succes)
- [x] Modal (@mzikherman)
- [x] Modal Footer (@mzikherman)
- [x] Navigation (@xtina-starr)
- [x] Text (@yuki24)
- [x] Forms (@l2succes)
- [x] Grid (@yuki24)

Loyalty Program Components
- [x]  Login Modal (@mzikherman)
- [x]  Facebook Button (@l2succes)
- [x]  Twitter Button (@l2succes)

**Comment by alloy** [comment]
> We're experimenting with ways to reuse the CSS for components in elan within reaction-force using a library like css-modules. However, it may make more sense to copy the styles directly into react components and just use styled-components.

I would prefer porting to the latter, because something like css-modules won’t work for if we’d ever want to share components between web and emission. Not that that’s definitely something we’ll be doing, but in order to know if it is a possibility we should try out the technologies that would be able to run on both platforms. (styled-components has RN support).

**Comment by l2succes** [comment]
@alloy Right, that's a good point. Alright, question answered then. We can stick to styled-components and copy styles as appropriate.

**Comment by alloy** [comment]
It would be interesting to know by the end roughly _how_ much of styling had to be ported.

**Comment by yuki24** [comment]
Generally speaking, styles and components should be decoupled otherwise we wouldn't be able to use any of it in a static website. I'm still learning about React native, but there must be a way to share decoupled styles even with React Native.

**Comment by l2succes** [comment]
@yuki24 That's actually not necessarily true in the age of components and css modules. To better grasp the design decisions and concepts behind CSS-in-JS. Check out the following talks. It helped me better understand why on you would embed css in your components.

[React: CSS in JS](https://speakerdeck.com/vjeux/react-css-in-js)
[The case for CSS modules - Mark Dalgleish](https://www.youtube.com/watch?v=zR1lOuyQEt8)

**Comment by mzikherman** [comment]
Closing this since we have these base components done! We still have a few pieces for the loyalty page, but those are their own issues.
